/*
 * © Copyright Lenovo 2015.
 *
 * LIMITED AND RESTRICTED RIGHTS NOTICE:
 *
 * If data or software is delivered pursuant a General Services Administration
 * "GSA" contract, use, reproduction, or disclosure is subject to
 * restrictions set forth in Contract No. GS-35F-05925.
*/
define({
		"allNodesTitle":"全部节点",
		"nodeName":"名称",
		"nodeStatus":"状态",
		"nodeType":"类别",
		"managementIP":"BMC IP",
		"OSIP":"OS IP",
		"CPUCores":"CPU核数",
		"usedMemory":"已用内存",
		"totalMemory":"总内存",
		"usedStorage":"已用存储",
		"totleStorage":"总存储",
		"CPUCoreUnit":"核",
		"showAllStatus":"查看全部状态",
		"showAllType":"查看全部类型",
		"nodesCount":"总节点数",
		"offStatus":"关机",
		"busyStatus":"忙碌",
		"workingStatus":"已占用",
		"idleStatus":"空闲",
		"headNodeType":"管理节点",
		"computeNodeType":"计算节点",
		"gpuNodeType":"GPU节点",
		"ioNodeType":"I/O节点",
		"loginNodeType":"登录节点",
		"groups":"自定义分组",
		"monitor_WebSSH":"SSH",
		"monitor_WebKVM":"iConsole",
		"monitor_turn_off":"关机",
		"monitor_turn_on":"开机",
		"monitor_turn_on_off":"开关",
		"success_turn_on":"开机成功",
		"error_turn_on":"开机失败",
		"success_turn_off":"关机成功",
		"error_turn_off":"关机失败",
		"g_node":"节点名称：",
		"prompt_node_details":"点击查看节点详细信息",
		"prompt_power_on":"点击开机",
		"prompt_power_off":"点击关机",
		"prompt_kvm":"点击进入iConsole窗口",
		"prompt_ssh":"点击进入SSH窗口",
		"sure_off":"确定要关闭以下节点吗?",
		"sure_on":"确定要开启以下节点吗?",
		"confirm":"确认",
		"cancel":"取消",
		"success":"操作成功",
		"error":"操作失败",
		"sProcessing":   "处理中...",
		"sLengthMenu":   "显示 _MENU_ 项结果",
		"sZeroRecords":  "没有匹配结果",
		"sInfo":         "显示第 _START_ 至 _END_ 项结果，共 _TOTAL_ 项",
		"sInfoEmpty":    "显示第 0 至 0 项结果，共 0 项",
		"sInfoFiltered": "(由 _MAX_ 项结果过滤)",
		"sInfoPostFix":  "",
		"sSearch":       "搜索:",
		"sUrl":          "",
		"sEmptyTable":     "表中数据为空",
		"sLoadingRecords": "载入中...",
		"sInfoThousands":  ",",
		"sFirst":    "首页",
		"sPrevious": "上页",
		"sNext":     "下页",
		"sLast":     "末页",
		"sSortAscending":  ": 以升序排列此列",
		"sSortDescending": ": 以降序排列此列"
});